#!/bin/bash
model=$(cat /etc/fw_model)

if [ ! -n "$model" ]; then
        model="EG500"
fi

echo model:$model

sleep 1

if [ ! -f "/usr/local/sbin/WebTunnelAgent" ]; then
    curl https://raw.githubusercontent.com/my-devices/agent-installer/master/install.sh | bash
fi

sleep 2

if [ "$1" == "reset" ]; then
    echo $1
    sudo cp config/hostapd.conf /etc/hostapd/hostapd.conf
    if [ "$model" = "EG324" ]; then
        sed -i "s/nl80211/rtl871xdrv/g" /etc/hostapd/hostapd.conf
    fi
    sudo cp config/090_raspap.conf /etc/dnsmasq.d/090_raspap.conf
    sudo cp config/090_br0.conf /etc/dnsmasq.d/090_br0.conf
    sudo cp config/dhcpcd.conf /etc/dhcpcd.conf
    sudo cp config/defaults.json /etc/raspap/networking/
    sudo cp Elastel/$model/etc/config/* /etc/config/
    sleep 1

    # reset wifi ssid
    sub_mac=$(ifconfig br0 | grep ether | awk '{print $2}' | cut -f 5-6 -d ":" | tr -d ":")
    ssid="$model"_"$sub_mac"
    sed -i "s/ssid.*/ssid=$ssid/" /etc/hostapd/hostapd.conf
fi

sudo cp config/090_raspap /etc/sudoers.d/090_raspap
sudo cp installers/service*.sh /etc/raspap/hostapd
sudo chown -c root:www-data /etc/raspap/hostapd/*.sh
sudo cp Elastel/$model/etc/init.d/* /etc/init.d/
sleep 1
sudo rm /etc/rc5.d/S01init-wifi
sudo rm /etc/rc5.d/S10failover
sudo rm /etc/rc5.d/S10lte
sudo rm /etc/rc5.d/S10dct
sudo rm /etc/rc5.d/S10daemon
sudo rm /etc/rc5.d/S10ddns
sudo rm /etc/rc5.d/S10macchina
sleep 1
sudo ln -s /etc/init.d/init-wifi /etc/rc5.d/S01init-wifi
sudo ln -s /etc/init.d/failover /etc/rc5.d/S10failover
sudo ln -s /etc/init.d/lte /etc/rc5.d/S10lte
sudo ln -s /etc/init.d/dct /etc/rc5.d/S10dct
sudo ln -s /etc/init.d/daemon /etc/rc5.d/S10daemon
sudo ln -s /etc/init.d/ddns /etc/rc5.d/S10ddns
sudo ln -s /etc/init.d/macchina /etc/rc5.d/S10macchina
sudo /etc/init.d/dct stop
sudo /etc/init.d/lte stop
sudo /etc/init.d/failover stop
sudo /etc/init.d/ddns stop
sleep 1
sudo cp -r Elastel/$model/usr/sbin/* /usr/sbin/
sudo cp -r Elastel/$model/usr/lib/* /usr/lib/
sudo cp -r Elastel/$model/usr/local/bin/* /usr/local/bin/
sleep 1
if [ $model = "EG410" ]; then
        if [ ! -e /dev/ttyACM0 ]; then
                sudo cp Elastel/$model/EG410_a/dctd /usr/sbin/dctd
        fi
fi

sleep 2

[ -n "$(pgrep daemond)" ] && {
    sudo kill -9 $(pgrep daemond) && sudo cp Elastel/$model/sbin/* /sbin/
}

echo -e "Complete to update, it will reboot system."
sleep 5
sudo systemctl reboot
